import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import { ThemeProvider } from "../../providers/Theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { setLangDir } from "@/src/utils/set-lang-dir";
import Header from "@/src/components/layout/header";
import { getTranslations } from "next-intl/server";
import Footer from "@/src/components/layout/footer";

// export const metadata: Metadata = {
//   icons: "./assets/images/logo.png",
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale });

  return {
    icons: "/assets/images/logo.png",
    title: t("metadata.title"),
    description: t("metadata.description"),
  };
}

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{ locale: string }>;
  children: React.ReactNode;
}>) {
  const { locale } = await params;
  return (
    <html suppressHydrationWarning dir={setLangDir(locale)} lang={locale}>
      <body>
        <NextIntlClientProvider>
          <ThemeProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
